# -*- coding: utf-8 -*-
"""Customer Segmentation & Retention Intelligence Platform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135z2sUkoCMcBkkhWIftJybwcBhUWoCZ-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import os

from google.colab import userdata
import os

os.environ["KAGGLE_API_TOKEN"] = userdata.get("CustomerSegmentation&RetentionIntelligencePlatform")

!kaggle datasets download -d vijayuv/onlineretail -p /content/Online_Retail && unzip -o /content/Online_Retail/onlineretail.zip -d /content/Online_Retail

df = pd.read_csv('/content/Online_Retail/OnlineRetail.csv', encoding='latin1')

df.head()

"""# Data Cleaning


"""

df.shape

df.info()

df.describe()

# checking the null value
df.isnull().sum()

# drop the CustomerID which have NULL
df = df.dropna(subset=['CustomerID'])

df.isnull().sum()

# checking the duplicate value
df.duplicated().sum()

# drop the duplicate value
df = df.drop_duplicates()

df.duplicated().sum()

# checking the how many cancalled InvoiceNo
df['InvoiceNo'].astype(str).str.startswith('C').sum()

# checking the how many cancalled InvoiceNo
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

# remove the those Quantity which have less the 1 Quantity
df = df[df['Quantity'] > 0]

df['Quantity'].min()

df.head()

# i want to know convert InviceDate to datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['InvoiceDate'].dtype

# Create Monetary value
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

df[['Quantity', 'UnitPrice', 'TotalAmount']].head()

# 9. Reference date
snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

# 10. Create RFM
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalAmount': 'sum'
})

rfm

# 11. Rename columns
rfm.columns = ['Recency', 'Frequency', 'Monetary']

# 12. Check
print(rfm.head())
print(rfm.shape)
print(rfm.describe())

"""# Exploratory Data Analysis

## Customer Question

1. How many customers do we have?

2. How many orders?

3. How much revenue?

4. What is the average order value?

5. Who are our top customers?

6. How many repeat customers exist?
"""

# How many customers do we have?

df.CustomerID.nunique()

# How many orders?
df.InvoiceNo.nunique()

# How much revenue?
df.TotalAmount.sum()

# What is the average order value?
aov = df.TotalAmount.sum() / df.InvoiceNo.nunique()
print("Average Order Value:", aov)

# Who are our top customers according to spend money ?
top_customers = df.groupby('CustomerID')['TotalAmount'].sum().sort_values(ascending=False).head(10)
print(top_customers)

# How many repeat customers exist?
customer_orders = df.groupby('CustomerID')['InvoiceNo'].nunique()
repeat_customers = customer_orders[customer_orders > 1].count()
print("Number of repeat customers:", repeat_customers)

# i want to see one customer how may order
df[df['CustomerID'] == 17850]

"""## Revenue questions

1. Which months generate the most revenue?

2. Which countries generate the most revenue?

3. Which products generate the most revenue?

4. How is revenue distributed?
"""

# Create Year-Month feature
df['InvoiceYearMonth'] = (
    df['InvoiceDate'].dt.to_period('M')
)

# Monthly revenue
monthly_revenue = (
    df.groupby('InvoiceYearMonth')['TotalAmount']
      .sum()
      .sort_index()
)

print("===== MONTHLY REVENUE =====")
print(monthly_revenue)

# i want to show how monthly revenew grow
monthly_revenue = df.groupby('InvoiceYearMonth')['TotalAmount'].sum()
monthly_revenue.plot(kind='line', marker='o')
plt.title('Monthly Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.show()

df['InvoiceYear'] = df['InvoiceDate'].dt.year

df

# Which countries generate the most revenue?

country_revenue = (
    df.groupby('Country')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

print("===== REVENUE BY COUNTRY =====")
print(country_revenue.head(10))

# i want to see the trend of revenue to accros the year
country_revenue = df.groupby('InvoiceYear')['TotalAmount'].sum()
country_revenue.plot(kind='line', marker='o')
plt.title('Country Revenue')
plt.xlabel('Year')
plt.ylabel('Revenue')
plt.show()

# Which products generate the most revenue?
product_revenue = df.groupby('Description')['TotalAmount'].sum().sort_values(ascending=False)
print(product_revenue)

# How is revenue distributed?
plt.hist(top_customers, bins=50)

plt.xlabel('Customer Revenue')
plt.ylabel('Number of Customers')
plt.title('Distribution of Revenue Across Customers')
plt.show()

"""# Customer-level feature engineering ⭐


"""

rfm['AverageOrderValue'] = rfm['Monetary'] / rfm['Frequency']

rfm

total_items = df.groupby('CustomerID')['Quantity'].sum()

rfm['TotalItems'] = total_items

unique_products = df.groupby('CustomerID')['StockCode'].nunique()

rfm['UniqueProducts'] = unique_products

customer_lifetime = (
    df.groupby('CustomerID')['InvoiceDate']
      .agg(lambda x: (x.max() - x.min()).days)
)

rfm['CustomerLifetime'] = customer_lifetime

"""# Features Selection"""

features = ['Recency', 'Frequency', 'Monetary']

rfm[features].describe()

rfm[features].skew()

rfm['Recency'].plot(kind = 'kde')

rfm['Frequency'].plot(kind = 'kde')

rfm['Monetary'].plot(kind = 'kde')

"""# Transform and scale the data

"""

rfm_model = rfm[features].copy()

# i want to normalized the feature of rtm_model
rfm_log = np.log1p(rfm_model)

rfm_log.skew()

import seaborn as sns

for col in features:
    plt.figure(figsize=(8, 5))
    sns.kdeplot(rfm_log[col], fill=True)
    plt.title(f'{col} After Log Transformation')
    plt.xlabel(col)
    plt.ylabel('Density')
    plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rfm_scaled = scaler.fit_transform(rfm_log)

rfm_scaled = pd.DataFrame(
    rfm_scaled,
    columns=features,
    index=rfm.index
)

rfm_scaled.describe()

"""# checking Outliers"""

for col in features:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=rfm_log[col])
    plt.title(f'{col} After Log Transformation')
    plt.show()

"""# Now we cluster the data"""

from sklearn.cluster import KMeans

inertia = []

K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(rfm_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))

plt.plot(K_range, inertia, marker='o')

plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')

plt.show()

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(rfm_scaled)

    score = silhouette_score(rfm_scaled, labels)
    silhouette_scores.append(score)

plt.figure(figsize=(8, 5))

plt.plot(K_range, silhouette_scores, marker='o')

plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score for Different K Values')

plt.show()

for k in [2, 3, 4, 5]:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(rfm_scaled)

    temp = rfm.copy()
    temp['Cluster'] = labels

    print(f"\n========== K = {k} ==========")

    print("Cluster sizes:")
    print(temp['Cluster'].value_counts().sort_index())

    print("\nAverage RFM:")
    print(temp.groupby('Cluster')[features].mean().round(2))

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

rfm.groupby('Cluster')[features].mean()

""" ### mytable tells us what each cluster looks like, but we haven't yet looked at how many customers are in each cluster and what percentage of revenue each cluster generates."""

cluster_summary = rfm.groupby('Cluster').agg(
    Customers=('Cluster', 'size'),
    AvgRecency=('Recency', 'mean'),
    AvgFrequency=('Frequency', 'mean'),
    AvgMonetary=('Monetary', 'mean'),
    TotalRevenue=('Monetary', 'sum')
)

cluster_summary['CustomerPercentage'] = (
    cluster_summary['Customers'] / len(rfm) * 100
)

cluster_summary['RevenuePercentage'] = (
    cluster_summary['TotalRevenue'] / rfm['Monetary'].sum() * 100
)

print(cluster_summary.round(2))

"""# Create the churn problem"""

print(df['InvoiceDate'].min())
print(df['InvoiceDate'].max())

max_date = df['InvoiceDate'].max()

cutoff_date = max_date - pd.Timedelta(days=90)

print("Maximum date:", max_date)
print("Cutoff date:", cutoff_date)

# Split the date

max_date = df['InvoiceDate'].max()

cutoff_date = max_date - pd.Timedelta(days=90)

historical_df = df[
    df['InvoiceDate'] < cutoff_date
].copy()

future_df = df[
    df['InvoiceDate'] >= cutoff_date
].copy()

print("Cutoff:", cutoff_date)
print("Historical data:", historical_df['InvoiceDate'].min(),
      "to", historical_df['InvoiceDate'].max())

print("Future data:", future_df['InvoiceDate'].min(),
      "to", future_df['InvoiceDate'].max())

# Create RFM using ONLY historical data

snapshot_date = cutoff_date

rfm_churn = historical_df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalAmount': 'sum'
})

rfm_churn.columns = ['Recency', 'Frequency', 'Monetary']

print(rfm_churn.head())

# Create the churn label
future_customers = future_df['CustomerID'].unique()

rfm_churn['Churn'] = 1

rfm_churn.loc[
    rfm_churn.index.isin(future_customers),
    'Churn'
] = 0

print(rfm_churn.head())
print()
print(rfm_churn['Churn'].value_counts())

print(
    rfm_churn['Churn']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

"""# Churn Feature Engineering"""

# Start with historical transactions
historical_df.head()

customer_features = historical_df.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda x: (cutoff_date - x.max()).days),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('TotalAmount', 'sum'),
    TotalItems=('Quantity', 'sum'),
    UniqueProducts=('StockCode', 'nunique')
)

customer_features

# Average Order Value
customer_features['AverageOrderValue'] = (
    customer_features['Monetary'] /
    customer_features['Frequency']
)

# Customer Lifetime

dates = historical_df.groupby('CustomerID')['InvoiceDate'].agg(
    FirstPurchase='min',
    LastPurchase='max'
)
customer_features['CustomerLifetime'] = (
    dates['LastPurchase'] - dates['FirstPurchase']
).dt.days

# Average Days Between Purchases
customer_features['AverageDaysBetweenPurchases'] = (
    (dates['LastPurchase'] - dates['FirstPurchase']) /
    (customer_features['Frequency'] - 1).replace(0, np.nan)
).dt.days

customer_features['AverageDaysBetweenPurchases'] = (
    customer_features['AverageDaysBetweenPurchases'].fillna(0)
)

customer_features.head()

customer_features['Churn'] = rfm_churn['Churn']

print(customer_features.isnull().sum())

print(customer_features.describe())

print(np.isinf(customer_features).sum())

"""# Now building Churn ML model"""

# 1. X and y
X = customer_features.drop('Churn', axis=1)
y = customer_features['Churn']

# 2. Train/Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 1. import
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split,cross_val_predict
from sklearn.metrics import ( accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix)

# ============================================================
# 2. PIPELINE
# ============================================================

log_reg_pipeline = Pipeline([

    ('scaler', StandardScaler()),

    ('model', LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])


# ============================================================
# 3. PARAMETER GRID
# ============================================================

param_grid_lr = {
    'model__C': [0.01, 0.1, 1, 10],
    'model__class_weight': [None, 'balanced']
}


# ============================================================
# 4. 5-FOLD CROSS VALIDATION
# ============================================================

cv_strategy = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ============================================================
# 5. GRID SEARCH
# ============================================================

lr_model = GridSearchCV(
    estimator=log_reg_pipeline,
    param_grid=param_grid_lr,
    cv=cv_strategy,
    scoring='f1',
    n_jobs=-1
)


# ============================================================
# 6. TRAIN
# ============================================================

lr_model.fit(X_train, y_train)


print("===== LOGISTIC REGRESSION TRAINING =====")

print("Best CV F1:",
      lr_model.best_score_)

print("Best Parameters:",
      lr_model.best_params_)


# ============================================================
# 7. OUT-OF-FOLD PROBABILITIES
# ============================================================
# IMPORTANT:
# We use X_train here, NOT X_test.
#
# These probabilities are used to select the threshold.
# This prevents us from using the test set to choose
# the threshold.

lr_prob_cv = cross_val_predict(
    lr_model.best_estimator_,
    X_train,
    y_train,
    cv=cv_strategy,
    method='predict_proba',
    n_jobs=-1
)[:, 1]


# ============================================================
# 8. THRESHOLD TUNING
# ============================================================

threshold_results = []

for threshold in [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]:

    y_pred_cv = (
        lr_prob_cv >= threshold
    ).astype(int)

    precision = precision_score(
        y_train,
        y_pred_cv
    )

    recall = recall_score(
        y_train,
        y_pred_cv
    )

    f1 = f1_score(
        y_train,
        y_pred_cv
    )

    threshold_results.append({
        'Threshold': threshold,
        'Precision': precision,
        'Recall': recall,
        'F1': f1
    })


threshold_results = pd.DataFrame(
    threshold_results
)


print("\n===== THRESHOLD RESULTS =====")

print(threshold_results)


# ============================================================
# 9. SELECT BEST THRESHOLD
# ============================================================
# Business requirement:
# Recall should be at least 80%.
#
# Among thresholds with Recall >= 80%,
# select the one with the highest F1.

valid_thresholds = threshold_results[
    threshold_results['Recall'] >= 0.80
]


if len(valid_thresholds) > 0:

    best_threshold = valid_thresholds.loc[
        valid_thresholds['F1'].idxmax(),
        'Threshold'
    ]

else:

    best_threshold = threshold_results.loc[
        threshold_results['F1'].idxmax(),
        'Threshold'
    ]


print("\n===== BEST THRESHOLD =====")

print("Best Threshold:",
      best_threshold)


# ============================================================
# 10. FINAL TEST PROBABILITY
# ============================================================
# IMPORTANT:
# X_test is used ONLY now for final evaluation.

lr_prob_test = lr_model.predict_proba(
    X_test
)[:, 1]


# ============================================================
# 11. FINAL TEST PREDICTION
# ============================================================

lr_pred_test = (
    lr_prob_test >= best_threshold
).astype(int)


# ============================================================
# 12. FINAL TEST RESULTS
# ============================================================

print("\n===== FINAL TEST RESULTS =====")

print("Threshold :",
      best_threshold)

print("Accuracy  :",
      accuracy_score(
          y_test,
          lr_pred_test
      ))

print("Precision :",
      precision_score(
          y_test,
          lr_pred_test
      ))

print("Recall    :",
      recall_score(
          y_test,
          lr_pred_test
      ))

print("F1        :",
      f1_score(
          y_test,
          lr_pred_test
      ))

print("ROC-AUC   :",
      roc_auc_score(
          y_test,
          lr_prob_test
      ))


# ============================================================
# 13. CONFUSION MATRIX
# ============================================================

print("\n===== CONFUSION MATRIX =====")

print(
    confusion_matrix(
        y_test,
        lr_pred_test
    )
)

"""# Random forest"""

# import
from sklearn.ensemble import RandomForestClassifier

# ============================================================
# 2. RANDOM FOREST MODEL
# ============================================================

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)


# ============================================================
# 3. PARAMETER GRID
# ============================================================

param_grid_rf = {

    'n_estimators': [100, 200],

    'max_depth': [None, 10, 20],

    'min_samples_split': [2, 5],

    'class_weight': [None, 'balanced']

}


# ============================================================
# 4. 5-FOLD CROSS VALIDATION
# ============================================================

cv_strategy = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ============================================================
# 5. GRID SEARCH
# ============================================================

rf_model = GridSearchCV(

    estimator=rf,

    param_grid=param_grid_rf,

    cv=cv_strategy,

    scoring='f1',

    n_jobs=-1
)


# ============================================================
# 6. TRAIN
# ============================================================

rf_model.fit(
    X_train,
    y_train
)


print("===== RANDOM FOREST TRAINING =====")

print(
    "Best CV F1:",
    rf_model.best_score_
)

print(
    "Best Parameters:",
    rf_model.best_params_
)


# ============================================================
# 7. OUT-OF-FOLD PROBABILITIES
# ============================================================
# IMPORTANT:
# Use X_train, NOT X_test.
#
# These probabilities are used to find
# the best threshold without using the test set.

rf_prob_cv = cross_val_predict(

    rf_model.best_estimator_,

    X_train,

    y_train,

    cv=cv_strategy,

    method='predict_proba',

    n_jobs=-1

)[:, 1]


# ============================================================
# 8. AUTOMATIC THRESHOLD TUNING
# ============================================================

threshold_results = []


for threshold in [
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60
]:

    y_pred_cv = (
        rf_prob_cv >= threshold
    ).astype(int)


    precision = precision_score(
        y_train,
        y_pred_cv
    )


    recall = recall_score(
        y_train,
        y_pred_cv
    )


    f1 = f1_score(
        y_train,
        y_pred_cv
    )


    threshold_results.append({

        'Threshold': threshold,

        'Precision': precision,

        'Recall': recall,

        'F1': f1

    })


threshold_results = pd.DataFrame(
    threshold_results
)


print("\n===== RANDOM FOREST THRESHOLD RESULTS =====")

print(threshold_results)


# ============================================================
# 9. AUTOMATICALLY SELECT BEST THRESHOLD
# ============================================================
# Requirement:
# Recall >= 80%
#
# Among those thresholds,
# choose the highest F1.

valid_thresholds = threshold_results[
    threshold_results['Recall'] >= 0.80
]


if len(valid_thresholds) > 0:

    best_threshold_rf = valid_thresholds.loc[
        valid_thresholds['F1'].idxmax(),
        'Threshold'
    ]

else:

    best_threshold_rf = threshold_results.loc[
        threshold_results['F1'].idxmax(),
        'Threshold'
    ]


print("\n===== BEST RANDOM FOREST THRESHOLD =====")

print(
    "Best Threshold:",
    best_threshold_rf
)


# ============================================================
# 10. FINAL TEST PROBABILITY
# ============================================================
# X_test is used ONLY now for final evaluation.

rf_prob_test = rf_model.predict_proba(
    X_test
)[:, 1]


# ============================================================
# 11. FINAL TEST PREDICTION
# ============================================================

rf_pred_test = (
    rf_prob_test >= best_threshold_rf
).astype(int)


# ============================================================
# 12. FINAL TEST RESULTS
# ============================================================

print("\n===== RANDOM FOREST FINAL TEST RESULTS =====")

print(
    "Threshold :",
    best_threshold_rf
)

print(
    "Accuracy  :",
    accuracy_score(
        y_test,
        rf_pred_test
    )
)

print(
    "Precision :",
    precision_score(
        y_test,
        rf_pred_test
    )
)

print(
    "Recall    :",
    recall_score(
        y_test,
        rf_pred_test
    )
)

print(
    "F1        :",
    f1_score(
        y_test,
        rf_pred_test
    )
)

print(
    "ROC-AUC   :",
    roc_auc_score(
        y_test,
        rf_prob_test
    )
)


# ============================================================
# 13. CONFUSION MATRIX
# ============================================================

print("\n===== RANDOM FOREST CONFUSION MATRIX =====")

print(
    confusion_matrix(
        y_test,
        rf_pred_test
    )
)

"""# XGBoost"""

# If XGBoost is not installed in Colab, run this once:
!pip install xgboost

# import
from xgboost import XGBClassifier

# ============================================================
# 2. XGBOOST MODEL
# ============================================================

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss',
    n_jobs=-1
)


# ============================================================
# 3. PARAMETER GRID
# ============================================================

param_grid_xgb = {

    'n_estimators': [100, 200],

    'max_depth': [3, 5],

    'learning_rate': [0.05, 0.1],

    'subsample': [0.8, 1.0],

    'colsample_bytree': [0.8, 1.0]

}


# ============================================================
# 4. 5-FOLD CROSS VALIDATION
# ============================================================

cv_strategy = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ============================================================
# 5. GRID SEARCH
# ============================================================

xgb_model = GridSearchCV(

    estimator=xgb,

    param_grid=param_grid_xgb,

    cv=cv_strategy,

    scoring='f1',

    n_jobs=-1
)


# ============================================================
# 6. TRAIN
# ============================================================

xgb_model.fit(
    X_train,
    y_train
)


print("===== XGBOOST TRAINING =====")

print(
    "Best CV F1:",
    xgb_model.best_score_
)

print(
    "Best Parameters:",
    xgb_model.best_params_
)


# ============================================================
# 7. OUT-OF-FOLD PROBABILITIES
# ============================================================
# IMPORTANT:
# Use X_train, NOT X_test.
#
# These probabilities are used to find
# the best threshold without using the test set.

xgb_prob_cv = cross_val_predict(

    xgb_model.best_estimator_,

    X_train,

    y_train,

    cv=cv_strategy,

    method='predict_proba',

    n_jobs=-1

)[:, 1]


# ============================================================
# 8. AUTOMATIC THRESHOLD TUNING
# ============================================================

threshold_results_xgb = []


for threshold in [
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60
]:

    y_pred_cv = (
        xgb_prob_cv >= threshold
    ).astype(int)


    precision = precision_score(
        y_train,
        y_pred_cv
    )


    recall = recall_score(
        y_train,
        y_pred_cv
    )


    f1 = f1_score(
        y_train,
        y_pred_cv
    )


    threshold_results_xgb.append({

        'Threshold': threshold,

        'Precision': precision,

        'Recall': recall,

        'F1': f1

    })


threshold_results_xgb = pd.DataFrame(
    threshold_results_xgb
)


print("\n===== XGBOOST THRESHOLD RESULTS =====")

print(threshold_results_xgb)


# ============================================================
# 9. AUTOMATICALLY SELECT BEST THRESHOLD
# ============================================================
# Requirement:
# Recall >= 80%
#
# Among those thresholds,
# choose the highest F1.

valid_thresholds_xgb = threshold_results_xgb[
    threshold_results_xgb['Recall'] >= 0.80
]


if len(valid_thresholds_xgb) > 0:

    best_threshold_xgb = valid_thresholds_xgb.loc[
        valid_thresholds_xgb['F1'].idxmax(),
        'Threshold'
    ]

else:

    best_threshold_xgb = threshold_results_xgb.loc[
        threshold_results_xgb['F1'].idxmax(),
        'Threshold'
    ]


print("\n===== BEST XGBOOST THRESHOLD =====")

print(
    "Best Threshold:",
    best_threshold_xgb
)


# ============================================================
# 10. FINAL TEST PROBABILITY
# ============================================================
# X_test is used ONLY now for final evaluation.

xgb_prob_test = xgb_model.predict_proba(
    X_test
)[:, 1]


# ============================================================
# 11. FINAL TEST PREDICTION
# ============================================================

xgb_pred_test = (
    xgb_prob_test >= best_threshold_xgb
).astype(int)


# ============================================================
# 12. FINAL TEST RESULTS
# ============================================================

print("\n===== XGBOOST FINAL TEST RESULTS =====")

print(
    "Threshold :",
    best_threshold_xgb
)

print(
    "Accuracy  :",
    accuracy_score(
        y_test,
        xgb_pred_test
    )
)

print(
    "Precision :",
    precision_score(
        y_test,
        xgb_pred_test
    )
)

print(
    "Recall    :",
    recall_score(
        y_test,
        xgb_pred_test
    )
)

print(
    "F1        :",
    f1_score(
        y_test,
        xgb_pred_test
    )
)

print(
    "ROC-AUC   :",
    roc_auc_score(
        y_test,
        xgb_prob_test
    )
)


# ============================================================
# 13. CONFUSION MATRIX
# ============================================================

print("\n===== XGBOOST CONFUSION MATRIX =====")

print(
    confusion_matrix(
        y_test,
        xgb_pred_test
    )
)

"""### Create the comparison table"""

# ============================================================
# FINAL MODEL COMPARISON
# ============================================================

# Logistic Regression

lr_result = {
    'Model': 'Logistic Regression',
    'Threshold': best_threshold,
    'Accuracy': accuracy_score(y_test, lr_pred_test),
    'Precision': precision_score(y_test, lr_pred_test),
    'Recall': recall_score(y_test, lr_pred_test),
    'F1': f1_score(y_test, lr_pred_test),
    'ROC-AUC': roc_auc_score(y_test, lr_prob_test)
}


# Random Forest

rf_result = {
    'Model': 'Random Forest',
    'Threshold': best_threshold_rf,
    'Accuracy': accuracy_score(y_test, rf_pred_test),
    'Precision': precision_score(y_test, rf_pred_test),
    'Recall': recall_score(y_test, rf_pred_test),
    'F1': f1_score(y_test, rf_pred_test),
    'ROC-AUC': roc_auc_score(y_test, rf_prob_test)
}


# XGBoost

xgb_result = {
    'Model': 'XGBoost',
    'Threshold': best_threshold_xgb,
    'Accuracy': accuracy_score(y_test, xgb_pred_test),
    'Precision': precision_score(y_test, xgb_pred_test),
    'Recall': recall_score(y_test, xgb_pred_test),
    'F1': f1_score(y_test, xgb_pred_test),
    'ROC-AUC': roc_auc_score(y_test, xgb_prob_test)
}


# Create comparison DataFrame

model_comparison = pd.DataFrame([
    lr_result,
    rf_result,
    xgb_result
])


print("===== MODEL COMPARISON =====")

print(model_comparison)

# Automatically select the best model
# ============================================================
# AUTOMATIC MODEL SELECTION
# ============================================================

minimum_recall = 0.80


# Keep only models with Recall >= 80%

eligible_models = model_comparison[
    model_comparison['Recall'] >= minimum_recall
]


# If at least one model satisfies the requirement

if len(eligible_models) > 0:

    # Among eligible models,
    # choose the model with highest F1

    best_model = eligible_models.loc[
        eligible_models['F1'].idxmax()
    ]

else:

    # If no model reaches 80% recall,
    # choose highest F1 overall

    best_model = model_comparison.loc[
        model_comparison['F1'].idxmax()
    ]


print("\n===== BEST MODEL =====")

print("Model     :", best_model['Model'])
print("Threshold :", best_model['Threshold'])
print("Accuracy  :", best_model['Accuracy'])
print("Precision :", best_model['Precision'])
print("Recall    :", best_model['Recall'])
print("F1        :", best_model['F1'])
print("ROC-AUC   :", best_model['ROC-AUC'])

model_comparison

"""## Explain the Model"""

# Get the automatically selected model
best_model_name = best_model['Model']

print("Selected Model:", best_model_name)


# Get the actual trained model
if best_model_name == 'Logistic Regression':
    final_model = lr_model.best_estimator_

elif best_model_name == 'Random Forest':
    final_model = rf_model.best_estimator_

elif best_model_name == 'XGBoost':
    final_model = xgb_model.best_estimator_

else:
    raise ValueError("Unknown model")


# ============================================================
# Extract feature importance
# ============================================================

if best_model_name == 'Logistic Regression':

    importance_values = (
        final_model
        .named_steps['model']
        .coef_[0]
    )

    # For Logistic Regression, keep the sign
    # because positive/negative has meaning.

elif best_model_name == 'Random Forest':

    importance_values = (
        final_model
        .feature_importances_
    )

elif best_model_name == 'XGBoost':

    importance_values = (
        final_model
        .feature_importances_
    )


# ============================================================
# Create DataFrame
# ============================================================

feature_importance = pd.DataFrame({

    'Feature': X_train.columns,

    'Importance': importance_values

})


# Sort by importance
feature_importance = feature_importance.sort_values(
    'Importance',
    ascending=False
)


print("\n===== FEATURE IMPORTANCE =====")

print(feature_importance)

"""## Customer-level prediction"""

# ============================================================
# CUSTOMER CHURN PREDICTION
# ============================================================

# Probability of churn
customer_features['ChurnProbability'] = (
    final_model.predict_proba(
        customer_features[X_train.columns]
    )[:, 1]
)


# Apply the automatically selected threshold

customer_features['ChurnPrediction'] = (
    customer_features['ChurnProbability']
    >= best_model['Threshold']
).astype(int)


print(
    customer_features[
        [
            'ChurnProbability',
            'ChurnPrediction'
        ]
    ].head()
)

"""## Create risk level"""

# ============================================================
# RISK LEVEL
# ============================================================

def risk_level(probability):

    if probability >= 0.70:
        return 'HIGH'

    elif probability >= 0.40:
        return 'MEDIUM'

    else:
        return 'LOW'


customer_features['RiskLevel'] = (
    customer_features['ChurnProbability']
    .apply(risk_level)
)


print(
    customer_features[
        [
            'ChurnProbability',
            'ChurnPrediction',
            'RiskLevel'
        ]
    ].head()
)

"""## Find the customer's main factors"""

# ============================================================
# CUSTOMER-LEVEL MODEL EXPLANATION
# ============================================================

def explain_customer(customer_id):

    # --------------------------------------------------------
    # 1. Check whether CustomerID exists
    # --------------------------------------------------------

    if customer_id not in customer_features.index:

        print(f"Customer {customer_id} not found.")

        return None


    # --------------------------------------------------------
    # 2. Get customer data
    # --------------------------------------------------------

    customer = customer_features.loc[customer_id]


    # --------------------------------------------------------
    # 3. Get model features
    # --------------------------------------------------------

    feature_names = list(X_train.columns)

    customer_input = customer[
        feature_names
    ].to_frame().T


    # --------------------------------------------------------
    # 4. Predict churn probability
    # --------------------------------------------------------

    churn_probability = final_model.predict_proba(
        customer_input
    )[0, 1]


    # --------------------------------------------------------
    # 5. Automatically selected threshold
    # --------------------------------------------------------

    threshold = best_threshold


    # --------------------------------------------------------
    # 6. Churn prediction
    # --------------------------------------------------------

    churn_prediction = int(
        churn_probability >= threshold
    )
    # --------------------------------------------------------
    #   Risk Level
    # --------------------------------------------------------
    risk = risk_level(churn_probability)


    # --------------------------------------------------------
    # 8. Explanation
    # --------------------------------------------------------

    explanations = []


    # ========================================================
    # LOGISTIC REGRESSION
    # ========================================================

    if best_model_name == 'Logistic Regression':

        # Get scaler
        scaler = final_model.named_steps['scaler']

        # Get LR model
        lr_model = final_model.named_steps['model']

        # Scale customer using SAME scaler
        customer_scaled = scaler.transform(
            customer_input
        )[0]

        # LR coefficients
        coefficients = lr_model.coef_[0]

        # Customer-specific contribution
        contributions = (
            customer_scaled * coefficients
        )

        for feature, value, contribution in zip(
            feature_names,
            customer_input.iloc[0],
            contributions
        ):

            if contribution > 0:

                effect = "Increases churn"

            else:

                effect = "Decreases churn"


            explanations.append({

                'Feature': feature,

                'Value': value,

                'Effect': effect,

                'Importance': abs(contribution)

            })


    # ========================================================
    # RANDOM FOREST
    # ========================================================

    elif best_model_name == 'Random Forest':

        import shap

        # SHAP explainer
        explainer = shap.TreeExplainer(
            final_model
        )

        shap_values = explainer.shap_values(
            customer_input
        )

        # Handle SHAP output
        if isinstance(shap_values, list):

            customer_shap = shap_values[1][0]

        else:

            customer_shap = shap_values[0]


        for feature, value, contribution in zip(
            feature_names,
            customer_input.iloc[0],
            customer_shap
        ):

            if contribution > 0:

                effect = "Increases churn"

            else:

                effect = "Decreases churn"


            explanations.append({

                'Feature': feature,

                'Value': value,

                'Effect': effect,

                'Importance': abs(contribution)

            })


    # ========================================================
    # XGBOOST
    # ========================================================

    elif best_model_name == 'XGBoost':

        import shap

        # SHAP explainer
        explainer = shap.TreeExplainer(
            final_model
        )

        shap_values = explainer(
            customer_input
        )

        customer_shap = shap_values.values[0]


        for feature, value, contribution in zip(
            feature_names,
            customer_input.iloc[0],
            customer_shap
        ):

            if contribution > 0:

                effect = "Increases churn"

            else:

                effect = "Decreases churn"


            explanations.append({

                'Feature': feature,

                'Value': value,

                'Effect': effect,

                'Importance': abs(contribution)

            })


    # --------------------------------------------------------
    # 9. Create explanation DataFrame
    # --------------------------------------------------------

    explanation_df = pd.DataFrame(
        explanations
    )


    explanation_df = explanation_df.sort_values(
        'Importance',
        ascending=False
    )


    # --------------------------------------------------------
    # 10. Print result
    # --------------------------------------------------------

    print("============================================")
    print("       CUSTOMER CHURN EXPLANATION")
    print("============================================")

    print(
        "Customer ID       :",
        customer_id
    )

    print(
        "Churn Probability :",
        round(churn_probability * 100, 2),
        "%"
    )

    print(
        "Prediction        :",
        "CHURN"
        if churn_prediction == 1
        else "NOT CHURN"
    )

    print(
        "Risk Level        :",
        risk
    )

    print(
        "Model             :",
        best_model_name
    )

    print(
        "Threshold         :",
        threshold
    )

    print("\n===== MAIN FACTORS =====")

    print(
        explanation_df.head(5)
    )


    # --------------------------------------------------------
    # 11. Return everything
    # --------------------------------------------------------

    return {

        'CustomerID': customer_id,

        'ChurnProbability': churn_probability,

        'ChurnPrediction': churn_prediction,

        'RiskLevel': risk,

        'Model': best_model_name,

        'Threshold': threshold,

        'Explanation': explanation_df

    }
explain_customer(12347)

"""##  CUSTOMER LIFETIME VALUE (CLV)"""

# Purchase frequency per year
customer_features['PurchaseFrequencyPerYear'] = np.where(
    customer_features['CustomerLifetime'] > 0,

    customer_features['Frequency'] /
    (customer_features['CustomerLifetime'] / 365),

    customer_features['Frequency']
)


# Avoid unrealistic extreme frequencies
customer_features['PurchaseFrequencyPerYear'] = (
    customer_features['PurchaseFrequencyPerYear']
    .clip(upper=365)
)


# Expected lifetime = 1 year
EXPECTED_LIFETIME_YEARS = 1


# CLV
customer_features['EstimatedCLV'] = (
    customer_features['AverageOrderValue'] *
    customer_features['PurchaseFrequencyPerYear'] *
    EXPECTED_LIFETIME_YEARS
)

"""## Risk × Value Matrix"""

# 1. CLV threshold
# Use median CLV to automatically divide customers
# into High Value and Low Value.

clv_threshold = customer_features['EstimatedCLV'].median()


# 2. Value classification

customer_features['ValueLevel'] = np.where(
    customer_features['EstimatedCLV'] >= clv_threshold,
    'High Value',
    'Low Value'
)


# 3. Risk × Value segment

def assign_risk_value_segment(row):

    if (
        row['ValueLevel'] == 'High Value'
        and
        row['RiskLevel'] in ['HIGH', 'MEDIUM']
    ):
        return 'Priority Retain'

    # High-value customers with low churn risk
    elif (
        row['ValueLevel'] == 'High Value'
        and
        row['RiskLevel'] == 'LOW'
    ):
        return 'VIP Loyal'

    # Low-value customers with high/medium churn risk
    elif (
        row['ValueLevel'] == 'Low Value'
        and
        row['RiskLevel'] in ['HIGH', 'MEDIUM']
    ):
        return 'Automated Campaign'

    # Low-value + low-risk
    else:
        return 'Normal Marketing'


customer_features['RiskValueSegment'] = (
    customer_features.apply(
        assign_risk_value_segment,
        axis=1
    )
)


# 4. Check results

print("===== RISK × VALUE MATRIX =====")

print(
    customer_features[
        [
            'EstimatedCLV',
            'ChurnProbability',
            'ChurnPrediction',
            'ValueLevel',
            'RiskLevel',
            'RiskValueSegment'
        ]
    ].head(20)
)

customer_features

"""## RETENTION RECOMMENDATION ENGINE"""

def retention_recommendation(row):

    if row['RiskValueSegment'] == 'Priority Retain':
        return 'Priority retention offer'

    elif row['RiskValueSegment'] == 'VIP Loyal':
        return 'Loyalty program'

    elif row['RiskValueSegment'] == 'Automated Campaign':
        return 'Low-cost automated campaign'

    else:
        return 'Normal marketing'


customer_features['RecommendedAction'] = (
    customer_features.apply(
        retention_recommendation,
        axis=1
    )
)

customer_features

